import purgecss from '@fullhuman/postcss-purgecss';

export default {
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
        ...(process.env.NODE_ENV === 'production' ? {
            '@fullhuman/postcss-purgecss': {
                content: [
                    './resources/**/*.blade.php',
                    './resources/**/*.vue',
                    './resources/**/*.js',
                ],
                defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
                safelist: {
                    standard: [
                        /^col-/,
                        /^row/,
                        /^container/,
                        /^navbar/,
                        /^nav-/,
                        /^btn/,
                        /^form-/,
                        /^card/,
                        /^modal/,
                        /^collapse/,
                        /^show/,
                        /^fade/,
                        /^d-/,
                        /^flex/,
                        /^align-/,
                        /^justify-/,
                        /^text-/,
                        /^bg-/,
                        /^p-/,
                        /^m-/,
                        /^py-/,
                        /^px-/,
                        /^my-/,
                        /^mx-/,
                        /^mt-/,
                        /^mb-/,
                        /^ms-/,
                        /^me-/,
                        /^pt-/,
                        /^pb-/,
                        /^ps-/,
                        /^pe-/,
                        /^g-/,
                        /^gap-/,
                        /^rounded/,
                        /^shadow/,
                        /^border/,
                        /^position-/,
                        /^w-/,
                        /^h-/,
                        /^fw-/,
                        /^fs-/,
                        /^lh-/,
                        /^overflow-/,
                        /^opacity-/,
                        /^swiper/,
                    ],
                },
            },
        } : {}),
    },
};
